import type { StatisticState, StudioPreset } from "../types";

export const DEFAULT_STATISTIC_STATE: StatisticState = {
  "title": "Production component",
  "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
  "label": "Component",
  "helper": "Native, buyer-ready, preview/export-honest output.",
  "id": "component-instance",
  "ariaLabel": "Component preview",
  "tabIndex": 0,
  "width": 520,
  "height": 320,
  "gap": 14,
  "padding": 24,
  "radius": 22,
  "borderWidth": 1,
  "borderStyle": "solid",
  "fontBucket": "google",
  "fontSearch": "",
  "systemFontIdx": 9,
  "googleFontFamily": "Inter",
  "fontSizeUnit": "px",
  "fontStyle": "normal",
  "textTransform": "none",
  "textDecoration": "none",
  "letterSpacing": 0,
  "letterSpacingUnit": "px",
  "lineHeight": 1.5,
  "radiusLinked": true,
  "radiusTL": 22,
  "radiusTR": 22,
  "radiusBR": 22,
  "radiusBL": 22,
  "shadowEnabled": true,
  "shadowX": 0,
  "shadowY": 8,
  "shadowBlur": 24,
  "shadowSpread": 0,
  "shadowOpacity": 0.25,
  "shadowColor": "#000000",
  "focusRingEnabled": true,
  "focusRingWidth": 2,
  "focusRingOffset": 2,
  "focusRingColor": "#38bdf8",
  "transitionDuration": 200,
  "transitionEasing": "ease",
  "background": "#0f172a",
  "foreground": "#e5eefb",
  "muted": "#94a3b8",
  "accent": "#38bdf8",
  "border": "#334155",
  "titleSize": 22,
  "bodySize": 14,
  "fontWeight": 700,
  "previewState": "default",
  "disabled": false,
  "role": "region",
  "value": "48.2K",
  "unit": "users",
  "prefix": "",
  "suffix": "active",
  "trend": "+12.4%",
  "trendDirection": "up",
  "showSparkline": true
};

export const STATISTIC_PRESETS: StudioPreset[] = [
  {
    "id": "premium-glass-compact",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "premium",
      "glass",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "premium-glass-spacious",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "premium",
      "glass",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "premium-soft-compact",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "premium",
      "soft",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "premium-soft-spacious",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "premium",
      "soft",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "premium-crisp-compact",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "premium",
      "crisp",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "premium-crisp-spacious",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "premium",
      "crisp",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "premium-hero-compact",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "premium",
      "hero",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "premium-hero-spacious",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "premium",
      "hero",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-glass-compact",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "editorial",
      "glass",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-glass-spacious",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "editorial",
      "glass",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-soft-compact",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "editorial",
      "soft",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-soft-spacious",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "editorial",
      "soft",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-crisp-compact",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "editorial",
      "crisp",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-crisp-spacious",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "editorial",
      "crisp",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-hero-compact",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "editorial",
      "hero",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "editorial-hero-spacious",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "editorial",
      "hero",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-glass-compact",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "admin",
      "glass",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-glass-spacious",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "admin",
      "glass",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-soft-compact",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "admin",
      "soft",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-soft-spacious",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "admin",
      "soft",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-crisp-compact",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "admin",
      "crisp",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-crisp-spacious",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "admin",
      "crisp",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-hero-compact",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "admin",
      "hero",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "admin-hero-spacious",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "admin",
      "hero",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-glass-compact",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "commerce",
      "glass",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-glass-spacious",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "commerce",
      "glass",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-soft-compact",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "commerce",
      "soft",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-soft-spacious",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "commerce",
      "soft",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-crisp-compact",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "commerce",
      "crisp",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-crisp-spacious",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "commerce",
      "crisp",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-hero-compact",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "commerce",
      "hero",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "commerce-hero-spacious",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "commerce",
      "hero",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-glass-compact",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "support",
      "glass",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-glass-spacious",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "support",
      "glass",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-soft-compact",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "support",
      "soft",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-soft-spacious",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "support",
      "soft",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-crisp-compact",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "support",
      "crisp",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-crisp-spacious",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "support",
      "crisp",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-hero-compact",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "support",
      "hero",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "support-hero-spacious",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "support",
      "hero",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-glass-compact",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "system",
      "glass",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-glass-spacious",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "system",
      "glass",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-soft-compact",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "system",
      "soft",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-soft-spacious",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "system",
      "soft",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-crisp-compact",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "system",
      "crisp",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-crisp-spacious",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "system",
      "crisp",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-hero-compact",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "system",
      "hero",
      "compact",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  },
  {
    "id": "system-hero-spacious",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "system",
      "hero",
      "spacious",
      "statistic",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "disabled": false,
      "role": "region",
      "value": "48.2K",
      "unit": "users",
      "prefix": "",
      "suffix": "active",
      "trend": "+12.4%",
      "trendDirection": "up",
      "showSparkline": true
    }
  }
];
