import type { StatisticState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: StatisticState, fileName = "statistic") : ExportPayload {
  return { fileName: `${fileName || "statistic"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: StatisticState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
    "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "function trendCopy() {",
    "  if (state.previewState === \"error\") return \"Metric needs attention\";",
    "  if (state.previewState === \"success\") return \"Metric is on target\";",
    "  if (state.trendDirection === \"down\") return `${state.trend} decrease`;",
    "  if (state.trendDirection === \"neutral\") return `${state.trend} change`;",
    "  return `${state.trend} increase`;",
    "}",
    "",
    "function trendColor() {",
    "  if (state.previewState === \"error\" || state.trendDirection === \"down\") return state.trendDownColor;",
    "  if (state.previewState === \"success\" || state.trendDirection === \"up\") return state.trendUpColor;",
    "  return state.trendNeutralColor;",
    "}",
    "",
    "export default function StatisticComponent() {",
    "  const panel = { width: state.width, minHeight: state.height, padding: state.padding, borderRadius: state.radius + \"px\", border: state.cardMode === \"minimal\" ? \"none\" : state.borderWidth + \"px \" + (state.borderStyle ?? \"solid\") + \" \" + (state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border), boxShadow: state.cardMode === \"minimal\" ? \"none\" : buildShadow(state), background: state.disabled && state.disabledUseCustomColors ? state.disabledBg : state.background, color: state.foreground, fontFamily: resolveFont(state), opacity: state.disabled ? (state.disabledOpacity ?? 0.5) : 1, cursor: state.disabled ? state.disabledCursor : undefined, transition: (state.transitionDuration > 0) ? \"opacity \" + state.transitionDuration + \"ms \" + (state.transitionEasing ?? \"ease\") : \"none\" };",
    "  const trend = trendCopy();",
    "  const statusColor = trendColor();",
    "  return (",
    "    <section id={state.id} role={state.role} aria-labelledby={`${state.id}-label`} aria-describedby={`${state.id}-description ${state.id}-trend`} tabIndex={state.tabIndex} style={panel} data-component=\"statistic\" data-preview-state={state.previewState}>",
    "      <div style={{ display: \"flex\", alignItems: \"flex-start\", justifyContent: \"space-between\", gap: 16 }}>",
    "        <div>",
    "          <p id={`${state.id}-label`} style={{ color: state.labelColor, fontSize: state.labelSize, fontWeight: 700, letterSpacing: \".16em\", textTransform: \"uppercase\" }}>{state.label}</p>",
    "          <h3 style={{ fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h3>",
    "        </div>",
    "        <span role=\"status\" style={{ border: \"1px solid \" + statusColor, borderRadius: 999, padding: \"4px 12px\", color: statusColor, fontSize: 12, fontWeight: 700 }}>{state.previewState}</span>",
    "      </div>",
    "      <p id={`${state.id}-description`} style={{ color: state.descriptionColor, fontSize: state.descriptionSize, marginTop: 8 }}>{state.description}</p>",
    "      <div style={{ marginTop: 24 }} aria-label={`${state.ariaLabel}: ${state.prefix}${state.value}${state.suffix ? ` ${state.suffix}` : \"\"}`}>",
    "        <p style={{ color: state.valueColor, fontSize: state.valueSize, fontWeight: state.valueFontWeight, lineHeight: 1, margin: 0, transition: state.transitionDuration > 0 ? \"font-size 200ms ease\" : \"none\" }}>",
    "          {state.unit && state.unitPosition === \"prefix\" ? <span style={{ marginRight: 8, color: state.unitColor, fontSize: state.unitSize, fontWeight: 700 }}>{state.unit}</span> : null}",
    "          <span style={{ color: state.prefixColor }}>{state.prefix}</span>",
    "          <data value={state.value}>{state.value}</data>",
    "          {state.unit && state.unitPosition === \"suffix\" ? <span style={{ marginLeft: 8, color: state.unitColor, fontSize: state.unitSize, fontWeight: 700 }}>{state.unit}</span> : null}",
    "        </p>",
    "        {state.suffix && <p style={{ marginTop: 8, color: state.suffixColor, fontSize: 14 }}>{state.suffix}</p>}",
    "      </div>",
    "      <div style={{ display: \"flex\", flexWrap: \"wrap\", alignItems: \"center\", gap: 12, marginTop: 20 }}>",
    "        <p id={`${state.id}-trend`} role=\"status\" style={{ display: \"inline-flex\", border: \"1px solid \" + statusColor, borderRadius: 999, padding: \"4px 12px\", color: statusColor, fontSize: 14, fontWeight: 700 }}>{trend}</p>",
    "        {state.comparisonLabel ? <span style={{ fontSize: 12, color: state.comparisonColor }}>{state.comparisonLabel}</span> : null}",
    "      </div>",
    "      {state.showSparkline && (",
    "        <svg aria-hidden=\"true\" viewBox=\"0 0 240 64\" style={{ display: \"block\", width: \"100%\", height: state.sparklineHeight, marginTop: 20, overflow: \"visible\" }}>",
    "          {state.sparklineType === \"area\" ? <polygon points=\"0,46 32,38 64,42 96,24 128,30 160,14 192,20 240,8 240,58 0,58\" fill={state.sparklineAreaColor} opacity=\"0.25\" /> : null}",
    "          {state.sparklineType === \"bar\" ? [0, 32, 64, 96, 128, 160, 192].map((x, i) => <rect key={x} x={x} y={[46, 38, 42, 24, 30, 14, 20][i]} width=\"20\" height={58 - [46, 38, 42, 24, 30, 14, 20][i]} fill={state.sparklineColor} rx=\"3\" />) : (",
    "            <polyline points=\"0,46 32,38 64,42 96,24 128,30 160,14 192,20 240,8\" fill=\"none\" stroke={state.sparklineColor} strokeWidth=\"5\" strokeLinecap=\"round\" strokeLinejoin=\"round\" />",
    "          )}",
    "          <line x1=\"0\" x2=\"240\" y1=\"58\" y2=\"58\" stroke={state.border} strokeWidth=\"2\" />",
    "        </svg>",
    "      )}",
    "      <p style={{ color: state.helpTextColor, fontSize: 12, marginTop: 16 }}>{state.helper}</p>",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}
